### ISSUE TITLE
Problems with Energy Date Selection

### ISSUE THREAD

**Issue by Waggers58** [MindFreeze/ha-sankey-chart#128]
**Checklist:**

- [Yes] I updated to the latest version available
- [Yes] I cleared the cache of my browser

**Release with the issue:**
v1.14.1
**Last working release (if known):**
n/k
**Browser and Operating System:**

Tried in both Chrome and Edge with Windows 11

**Description of problem:**

I am getting errors with the Sankey Chart card when I use Energy Date Selection.

The data all comes from my Solis Inverter. I am feeding in solar generated, battery charge, battery discharge, grid import and grid output figures. I am calculating my Consumption in a template using the following formula:

Consumption = Solar Generation + Grid Import + Battery Discharge – Grid Export – Battery Charge 

All the values are in kWh and represent energy used so far today. See below for the code: 

[Sankey Test.txt](https://github.com/MindFreeze/ha-sankey-chart/files/12708248/Sankey.Test.txt)

When the energy_date_selection is set to false, everything is ok.  The chart looks correct and the values correspond to the data being feed in:

![Sankey Chart Off](https://github.com/MindFreeze/ha-sankey-chart/assets/93612342/2cea95c1-7d60-490a-a148-b6ba6f1f1eca)

When I set energy_date_selection to true I have issues.  Most of the values change and the Consumption value is clearly wrong – it exceeds the total output of the inverter.
 
![Sankey Chart On](https://github.com/MindFreeze/ha-sankey-chart/assets/93612342/7c44ef60-42ed-46f0-ac8b-3d3a268cee51)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by MindFreeze** [comment]
Does date selection work properly in the HA Energy dashboard? I use the same API to get data by date range. It is basically {value at end of day} - {value at beginning of the day}

**Comment by MindFreeze** [comment]
This should be fixed in v1.16.1 . Please reopen if it is not

**Comment by Waggers58** [comment]
Updated to v1.16.1 today and unfortunately I have to inform you that the error is still not fixed.  Please Re-open.
![sankey](https://github.com/MindFreeze/ha-sankey-chart/assets/93612342/772b4939-2cc3-4727-81da-39a5b4857263)

I can confirm that the date selection does work on the HA Energy dashboard and it shows Home consumption to be 8.3kWh.

**Comment by MindFreeze** [comment]
@Waggers58 This looks like an issue with your template sensor. Try setting adding `state_class: total` to it
