### ISSUE TITLE
Auto config for energy dashboard

### ISSUE THREAD

**Issue by MindFreeze** [MindFreeze/ha-sankey-chart#60]
In theory the card can be auto configured for energy with the data from the energy dashboard.

The most basic resulting config would be `${energy sources} -> ${individual consumers}` with probably a sum in the middle.

An even better config would group the consumers by area as well. So:
`${energy sources} -> ${total consumed} -> ${areas from HA} -> ${individual consumers}`

- [x] config sources and devices
- [x] add areas
- [x] output generated config
- [ ] unit tests

**Comment by house2001** [comment]
Hi, 

I'm getting an error when building a chart with `autoconfig:  `

Is it helpful to show the generated yaml and error? This is a great project and I know it's in beta still.

**Comment by MindFreeze** [comment]
Yes, please share

**Comment by martinarva** [comment]
Could somebody share the lovelace YAML that works. I have tried everything but get the result:
<img width="579" alt="Screenshot 2023-01-02 at 16 39 03" src="https://user-images.githubusercontent.com/77044330/210245895-b571890c-88a9-4b83-83eb-82f0d3611ccf.png">

**Comment by kamaradclimber** [comment]
I have the same output, should we open an dedicated issue?

**Comment by MindFreeze** [comment]
No need for a dedicated issue but I do need the outputof this command in the dev console (F12) `JSON.stringify((await hassConnection).conn._energy.prefs.energy_sources)` and/or a picture of the energy-distribution card in your energy dashboard

**Comment by kamaradclimber** [comment]
```
"[{\"type\":\"grid\",\"flow_from\":[{\"stat_energy_from\":\"sensor.home_energy_meter_gen5_electric_consumed_kwh\",\"stat_cost\":null,\"entity_energy_price\":\"sensor.electricity_cost\",\"number_energy_price\":null}],\"flow_to\":[],\"cost_adjustment_day\":0},{\"type\":\"gas\",\"stat_energy_from\":\"sensor.gaz_consumption_in_kwh\",\"stat_cost\":null,\"entity_energy_price\":null,\"number_energy_price\":0.1563},{\"type\":\"water\",\"stat_energy_from\":\"sensor.water_total\",\"stat_cost\":null,\"entity_energy_price\":null,\"number_energy_price\":null}]"
```

![image](https://user-images.githubusercontent.com/503537/211484548-8aa7984d-7022-42f1-b46c-fe02b0d7c2fb.png)

**Comment by kamaradclimber** [comment]
Thanks for your reply.

I still get the "not found" message (present in previous version as well) and a new debug object:
![2023-01-10-165509_2278x288_scrot](https://user-images.githubusercontent.com/503537/211599353-9524e851-ce7e-4e89-9996-6e0ef113ec0d.png)

**Comment by Xitro01** [comment]
Same problem here.

Running:
Home Assistant 2023.1.5
Supervisor 2022.12.1
Operating System 9.4
Frontend-versie: 20230110.0 - latest

Sankey Chart: v1.8.0

Error in console log:
```
Object
code
: 
"not_found"
message
: 
"Entity not found"
[[Prototype]]
: 
Object
constructor
: 
ƒ Object()
hasOwnProperty
: 
ƒ hasOwnProperty()
isPrototypeOf
: 
ƒ isPrototypeOf()
propertyIsEnumerable
: 
ƒ propertyIsEnumerable()
toLocaleString
: 
ƒ toLocaleString()
toString
: 
ƒ toString()
valueOf
: 
ƒ valueOf()
__defineGetter__
: 
ƒ __defineGetter__()
__defineSetter__
: 
ƒ __defineSetter__()
__lookupGetter__
: 
ƒ __lookupGetter__()
__lookupSetter__
: 
ƒ __lookupSetter__()
__proto__
: 
(...)
get __proto__
: 
ƒ __proto__()
set __proto__
: 
ƒ __proto__()
```

**Comment by MindFreeze** [comment]
That could be it. I'll try to reproduce with a missing entity.

**Comment by martinarva** [comment]
I have some missing entities as well, but I don't want to delete them, because when it will delete history as well from energy dashboard. For example, my PV entity changed.
![Screenshot 2023-01-18 at 12 17 36](https://user-images.githubusercontent.com/77044330/213145960-a983c7fd-bcdd-4e9f-8556-1d3c476ea906.png)

**Comment by martinarva** [comment]
> 1.8.2 will ignore missing entities

<img width="510" alt="Screenshot 2023-01-18 at 16 36 35" src="https://user-images.githubusercontent.com/77044330/213199504-328a8219-1f98-4776-8619-a9f61a102400.png">

Now a new kind of error

**Comment by Dutchy-79** [comment]
Autoconfig error
![Screenshot_20230118_153610_Home Assistant](https://user-images.githubusercontent.com/22749572/213205859-016f4fba-e8f7-4486-835e-171f092df787.png)
![Screenshot_20230118_160229_Home Assistant](https://user-images.githubusercontent.com/22749572/213206074-696cd95d-8e0d-49cc-bd5c-92a86f8773b6.png)

**Comment by MindFreeze** [comment]
@martinarva try v1.9.0 . I was only checking the consumers before. Now it checks producers as well

**Comment by MindFreeze** [comment]
Not expected. You are the second person to report this. Mind posting a pic of your energy distribution card?

**Comment by Xitro01** [comment]
> Not expected. You are the second person to report this. Mind posting a pic of your energy distribution card?

Already did this, but strangely enough my screenshot did not go through, hopefully now it works:
![Schermafbeelding 2023-01-18 171142](https://user-images.githubusercontent.com/19844787/213229944-f58f67ec-9b58-4630-a7d9-0d9c3f40d3e4.png)

**Comment by Xitro01** [comment]
> I mean the card that is called Energy Distribution, in the Energy dashboard. On the right in desktop mode

![D5FBBD98-E898-4955-859B-90C40DCCDA75](https://user-images.githubusercontent.com/19844787/213252976-9145ce68-848e-4105-9529-cb086a3e0a8f.png)

**Comment by MindFreeze** [comment]
Looks quite similar to the other report. Maybe grid export is causing this. I'll try to reproduce this tomorrow

**Comment by martinarva** [comment]
![image](https://user-images.githubusercontent.com/77044330/213282459-4659f1e0-b518-4bca-8452-c8a09ffecbbd.png)

Now a new error in every sankey chart

**Comment by N0BaDaY** [comment]
Same issue, even after going back to 1.8.2
![4D4F56FE-CA5E-429A-B023-1FC6914B9CE1](https://user-images.githubusercontent.com/60921630/213288502-50faed49-23a2-4614-96c2-36f26bd34df7.jpeg)

**Comment by Dutchy-79** [comment]
![Screenshot_20230118_193253_Home Assistant](https://user-images.githubusercontent.com/22749572/213292203-e848d7c0-6aa6-4949-9bbf-bc4a9549031b.png)

Reboot and stays the same, v1. 9

**Comment by MindFreeze** [comment]
I think I fixed the export problem. Please let me know

**Comment by martinarva** [comment]
> I think I fixed the export problem. Please let me know


Yes, graph in general works now, but autoconfig still dont:
![Uploading Screenshot 2023-01-19 at 15.17.23.png…]()

**Comment by martinarva** [comment]
![Screenshot 2023-01-19 at 15 24 24](https://user-images.githubusercontent.com/77044330/213454127-3bdd8e1c-1543-4c05-bbe6-7846803e33b5.png)
![Screenshot 2023-01-19 at 15 23 36](https://user-images.githubusercontent.com/77044330/213454134-c1e148f3-6d52-4628-99fa-be43e92079c4.png)

**Comment by Xitro01** [comment]
Just like the rest, I get the following error now:

```
Custom element doesn't exist: sankey-chart.
type: custom:sankey-chart
autoconfig:
  print_yaml: false
```

**Comment by Dutchy-79** [comment]
> 

Going from v1. 9 to 1.9.2 solved that for me somehow.

**Comment by MindFreeze** [comment]
@Xitro01 HA cached the bad version somewhere else and not only the normal browser cache. WebWorkers or something similar, haven't investigated. You have to clear all application data and unregister wokers, or just wait for it to expire. Took a couple of hours for me.

**Comment by Xitro01** [comment]
> @Xitro01 HA cached the bad version somewhere else and not only the normal browser cache. WebWorkers or something similar, haven't investigated. You have to clear all application data and unregister wokers, or just wait for it to expire. Took a couple of hours for me.

The HA update this morning finally fixed it. Washer and dryer are not connected anymore, getting new ones this morning. So the missing entities issue is resolved.
But still missing labels:

![Schermafbeelding 2023-01-20 085422](https://user-images.githubusercontent.com/19844787/213645154-1795758b-6f87-4b9c-91d2-e4bbe1a315ce.png)

**Comment by N0BaDaY** [comment]
Fixed with v1.9.2 👍🏻

**Comment by Xitro01** [comment]
Another option from me, I found out that I could just use "show_names: true".
![Knipsel](https://user-images.githubusercontent.com/19844787/213918289-de1a09e7-d72a-4062-8c86-2b1a08750c1e.PNG)

- I expect "No Area" to be picked up from the location of the consumer entities.
- I expect "Unknown" to be called "Other"
- I expect consumer entities to be sorted by how much they consumed.
- I expect Envoy .... to be just called "Solar" just like the "Electricity meter....".

Also as mentioned in my post before:
It doesn't really seem to take into account that some solar power might not be used yourself, that it's delivered back.
Should actually say: 58,2 from net, 9,4 used in solar (and 6,6 delivered back to the grid)

**Comment by Dutchy-79** [comment]
You can setup yourself 
![Screenshot_20230122_122924_Home Assistant](https://user-images.githubusercontent.com/22749572/213918617-716d054d-47a7-40e5-8c1d-1dae52b4cf28.png)

**Comment by Xitro01** [comment]
> You can setup yourself ![Screenshot_20230122_122924_Home Assistant](https://user-images.githubusercontent.com/22749572/213918617-716d054d-47a7-40e5-8c1d-1dae52b4cf28.png)

Beats the purpose of 'autoconfig' the information is already there to be used.

**Comment by Dutchy-79** [comment]
It's used but configured differently. Autoconfig is just a basic to get started imo.

**Comment by N0BaDaY** [comment]
I still don't understand how to configure the autoconfig. I am just curious what it will come up with but I can't get it to work...don't know where to put the " type: energy-date-selection" No matter where I put this it comes up with error messages. Anyone has a clue?

<img width="979" alt="Scherm­afbeelding 2023-01-23 om 10 08 31" src="https://user-images.githubusercontent.com/60921630/214003191-f42dc080-290c-411e-b38e-3d0fb4d1a40b.png">

this doesn't work:
<img width="418" alt="Scherm­afbeelding 2023-01-23 om 10 15 27" src="https://user-images.githubusercontent.com/60921630/214003415-166b023f-71ae-44f7-bc39-21e39b6d11c3.png">

**Comment by Dutchy-79** [comment]
I had the same problem but the Readme makes it look wrong.

You need 2 cards

Card 1
Custom card
type: energy-data-selection

Card 2
Sankey card
type: custom:sankey-chart
energy_date_selection: true
autoconfig:
  print_yaml: true

**Comment by N0BaDaY** [comment]
Thanks a lot, it works now:

<img width="1140" alt="Scherm­afbeelding 2023-01-23 om 11 49 25" src="https://user-images.githubusercontent.com/60921630/214021660-31df857a-45f5-4a55-9323-909530f023fd.png">

**Comment by MindFreeze** [comment]
Yep, the README assumes a yaml mode dashboard. I hadn't used UI mode until recently and am just now seeing the differences. Working on improving this in #77

@Xitro01 autoconfig is indeed just a starting point. This is the point of the `print_yaml` option. `show_names` should be turned on by default, I guess, but you other expectations are very subjective.

**Comment by martinarva** [comment]
In my case it's still not working:
![Screenshot 2023-01-25 at 17 44 49](https://user-images.githubusercontent.com/77044330/214608538-5e308077-5aea-48fb-ae13-efe84e26611b.png)

**Comment by N0BaDaY** [comment]
It worked all right but now it doesn't any more...same error message as above..I haven't changed anything apart from the update tot the latest version
